stages:
  - build
  - test
  - deploy

image:
  name: docker/compose:latest

services:
  - docker:dind

build-backend:
  stage: build
  before_script:
    - echo "Rodando o build do back"
  script:
    - cd backend
    - docker build -t backend .
  after_script:
    - echo "Build backend OK!"

build-frontend:
  stage: build
  before_script:
    - echo "Rodando o build do front"
  script:
    - cd frontend
    - docker build -t frontend .
  after_script:
    - echo "Build frontend OK!"

test-backend:
  stage: test
  before_script:
    - echo "Rodando os testes do back"
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Testes backend OK!"

test-frontend:
  stage: test
  before_script:
    - echo "Rodando os testes do front"
  script:
    - docker-compose run --entrypoint "npm run test" frontend
  after_script:
    - echo "Testes frontend OK!"

deploy-images:
  stage: deploy
  before_script:
    - echo "Subindo as imagens para o dockerhub"
    - echo "Autenticando com dockerhub"
    - docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PASS
  script:
    - cd frontend
    - docker build -t frontend:latest .
    - docker push $DOCKERHUB_ID/frontend:latest
    - docker build -f ../backend -t backend:latest .
    - docker push $DOCKERHUB_ID/backend:latest
  after_script:
    - docker logout
    - echo "Imagens publicadas no DockerHub!"    